"""
Apply Data Builder Service.

Normalizes agent outputs into a clean, flat format that the frontend
can directly POST to the .NET `POST /api/Plan/{id}/apply-ai` endpoint.

Handles:
- Itinerary: maps stop names → resolved placeIds, includes flight airport items,
  merges end_day→start_day into overnight hotel stays
- Budget: merges aggregated_costs into flat expense items with ExpenseCategory mapping
- Packing lists: passes through from preparation_agent
- Notes: passes through from preparation_agent
- Plan metadata: start/end dates, currency from plan_context
"""

import logging
import re
import unicodedata
from typing import Any

logger = logging.getLogger(__name__)


def _normalize_name(name: str) -> str:
    """Normalize a place name for fuzzy matching.
    
    Strips parenthetical suffixes, extra whitespace, and normalizes Unicode
    so that 'Temple of Literature (Văn Miếu)' matches 'Temple of Literature'.
    """
    if not name:
        return ""
    # Remove parenthetical suffix: "Name (extra)" → "Name"
    s = re.sub(r'\s*\([^)]*\)\s*$', '', name)
    # Collapse whitespace
    s = re.sub(r'\s+', ' ', s).strip()
    # NFC normalize unicode so diacritics compare consistently
    s = unicodedata.normalize('NFC', s)
    return s.lower()


def _lookup_place_id(name: str, name_to_place_id: dict[str, str]) -> str:
    """Look up placeId with fallback strategies.
    
    1. Exact lowercase match
    2. Normalized match (strip parenthetical, normalize unicode)
    3. Substring containment (stop name contains a known name, or vice versa)
    """
    if not name:
        return ""
    key = name.lower()
    
    # 1. Exact match
    if key in name_to_place_id:
        return name_to_place_id[key]
    
    # 2. Normalized match
    norm_key = _normalize_name(name)
    if norm_key in name_to_place_id:
        return name_to_place_id[norm_key]
    
    # 3. Substring containment: check if stop name contains any known name or vice versa
    for known_name, pid in name_to_place_id.items():
        if len(known_name) >= 4 and (known_name in key or key in known_name):
            return pid
        # Also try normalized versions
        norm_known = _normalize_name(known_name)
        if len(norm_known) >= 4 and (norm_known in norm_key or norm_key in norm_known):
            return pid
    
    return ""

# ── ExpenseCategory mapping ──────────────────────────────────────────────
# Maps cost_aggregator category keys → .NET ExpenseCategory enum values
# and preparation_agent budget "type" fields → .NET enum
AGGREGATED_CATEGORY_MAP = {
    "flights": "Transport",
    "accommodation": "Accomodation",
    "attractions": "Activities",
    "restaurants": "FoodAndDrink",
}

PREP_BUDGET_TYPE_MAP = {
    "Food & Drinks": "FoodAndDrink",
    "Transport": "Transport",
    "Activities": "Activities",
    "Shopping": "Shopping",
    "Other": "Other",
}

# Roles to SKIP entirely (origin-side airport events)
SKIP_ROLES = {"outbound_departure", "return_arrival"}


def _parse_time_minutes(time_str: str) -> int:
    """Parse "HH:MM" to total minutes since midnight."""
    if not time_str:
        return 0
    try:
        parts = time_str.split(":")
        return int(parts[0]) * 60 + int(parts[1])
    except (ValueError, IndexError):
        return 0


# ── Itinerary ────────────────────────────────────────────────────────────

def _get_roles(stop: dict) -> set[str]:
    """Extract roles as a set from stop. Handles both list and legacy string format."""
    role = stop.get("role", [])
    if isinstance(role, str):
        return {role}
    if isinstance(role, list):
        return set(role)
    return set()


def _has_role(stop: dict, role_name: str) -> bool:
    return role_name in _get_roles(stop)


def _primary_role(stop: dict) -> str:
    """Get the primary role for display/API purposes.
    
    Priority: boundary roles > hotel logistics > activity roles.
    """
    roles = _get_roles(stop)
    # Boundary roles take priority
    for r in ("outbound_arrival", "return_departure", "start_day", "end_day"):
        if r in roles:
            return r
    # Hotel logistics
    for r in ("check_in", "check_out", "luggage_drop", "luggage_pickup", "rest"):
        if r in roles:
            return r
    # Activity roles
    for r in ("attraction", "generic", "lunch", "dinner"):
        if r in roles:
            return r
    # Fallback
    return sorted(roles)[0] if roles else ""


# Role-based note descriptions for context
_ROLE_NOTE_FRAGMENTS = {
    "check_in": "Check-in",
    "check_out": "Check-out",
    "luggage_drop": "Drop luggage",
    "luggage_pickup": "Pick up luggage",
    "rest": "Rest",
    "start_day": "Start day",
    "end_day": "Overnight stay",
    "outbound_arrival": "Arrival",
    "return_departure": "Departure",
}


def _generate_note(stop: dict) -> str | None:
    """Extract note generated by the LLM, with smart fallbacks.
    
    Priority: LLM-generated note > role-specific fallback > stop name.
    This prevents empty items in the frontend when no placeId is available.
    """
    note = stop.get("note", "")
    if note:
        return note
    
    roles = _get_roles(stop)
    name = stop.get("name", "")
    
    # Role-specific descriptive fallbacks for logistics stops
    # (these roles usually have hotel name as `name`, which isn't useful as a note)
    ROLE_FALLBACKS = {
        "rest": "Nghỉ ngơi",
        "luggage_drop": "Gửi hành lý",
        "luggage_pickup": "Nhận lại hành lý",
        "check_in": "Nhận phòng",
        "check_out": "Trả phòng",
        "end_day": "Nghỉ ngơi qua đêm",
        "start_day": "Khởi hành",
    }
    
    # Check if any role has a descriptive fallback
    for role in roles:
        if role in ROLE_FALLBACKS:
            return ROLE_FALLBACKS[role]
    
    # For other roles (generic, lunch, dinner, etc.), use stop name
    needs_fallback = roles & {
        "generic", "lunch", "dinner",
        "outbound_arrival", "return_departure",
    }
    if needs_fallback and name:
        return name
    
    return None

def _build_itinerary_days(
    agent_outputs: dict[str, Any],
    plan_context: dict[str, Any],
) -> list[dict]:
    """Build itinerary days from itinerary_agent output.

    Includes:
    - Attractions, meals, generic activities with resolved placeIds
    - Outbound flight (outbound_arrival): full flight block
    - Return flight (return_departure): airport wait + flight block
    - Hotel overnight (end_day → start_day merge): single overnight item
    
    Skips:
    - outbound_departure, return_arrival (origin-side events)
    - start_day when previous day had end_day for same hotel
    """
    itinerary_data = agent_outputs.get("itinerary_agent", {})
    resolved_places = itinerary_data.get("resolved_places", {})
    restaurant_data = agent_outputs.get("restaurant_agent", {})
    flight_data = agent_outputs.get("flight_agent", {})

    # Build name → placeId lookup from resolved places
    # Uses both exact lowercase and normalized keys for robust matching
    name_to_place_id: dict[str, str] = {}
    for group_key in ("airports", "hotels", "attractions"):
        for item in resolved_places.get(group_key, []):
            resolved = item.get("resolved")
            if resolved:
                place_id = resolved.get("placeId", "")
                original_name = item.get("name", "")
                resolved_title = resolved.get("title", "")
                if place_id:
                    if original_name:
                        name_to_place_id[original_name.lower()] = place_id
                        norm = _normalize_name(original_name)
                        if norm:
                            name_to_place_id[norm] = place_id
                    if resolved_title:
                        name_to_place_id[resolved_title.lower()] = place_id
                        norm = _normalize_name(resolved_title)
                        if norm:
                            name_to_place_id[norm] = place_id
    logger.info(f"🔨 [APPLY_DATA] name_to_place_id has {len(name_to_place_id)} entries")

    # Build restaurant lookup by (day, meal_type) → {name, place_id, note}
    restaurant_by_slot: dict[tuple[int, str], dict] = {}
    if restaurant_data and not restaurant_data.get("skipped"):
        for meal in restaurant_data.get("meals", []):
            r_day = meal.get("day", -1)
            r_type = meal.get("meal_type", "")
            r_name = meal.get("name", "")
            r_place_id = meal.get("place_id", "")
            r_note = meal.get("note", "")
            if r_day >= 1 and r_type and r_name:
                restaurant_by_slot[(r_day, r_type)] = {
                    "name": r_name,
                    "place_id": r_place_id,
                    "note": r_note,
                }

    # Extract flight times for outbound/return items
    outbound_flight = flight_data.get("recommend_outbound_flight") if flight_data else None
    return_flight = flight_data.get("recommend_return_flight") if flight_data else None

    # Pre-process: build lookup of next day's start_day departure time,
    # and track which hotels had end_day (for start_day skipping)
    all_days = itinerary_data.get("days", [])
    end_day_hotels: dict[int, str] = {}  # day_idx → hotel name

    # Also collect start_day departure times per day for overnight duration calc
    start_day_departures: dict[int, str] = {}  # day_idx → departure time "HH:MM"
    for day_data in all_days:
        day_idx = day_data.get("day", 1)
        for stop in day_data.get("stops", []):
            if _has_role(stop, "start_day"):
                start_day_departures[day_idx] = stop.get("departure", "")
            if _has_role(stop, "end_day"):
                end_day_hotels[day_idx] = stop.get("name", "")

    days = []
    for day_data in all_days:
        day_idx = day_data.get("day", 1)
        items = []

        for stop in day_data.get("stops", []):
            roles = _get_roles(stop)
            role = _primary_role(stop)
            name = stop.get("name", "")
            arrival = stop.get("arrival", "")
            departure = stop.get("departure", "")

            # ── Skip origin-side airport events ──
            if roles & SKIP_ROLES:
                continue

            # ── Skip start_day if previous night had end_day for same hotel ──
            if "start_day" in roles:
                prev_day_idx = day_idx - 1
                prev_end_hotel = end_day_hotels.get(prev_day_idx, "")
                if prev_end_hotel and prev_end_hotel.lower() == name.lower():
                    # Already covered by previous day's overnight stay
                    continue

            # ── Outbound arrival (destination airport) ──
            if "outbound_arrival" in roles:
                # When flight data exists: show full flight block
                # When no flight data (draft): use itinerary arrival/departure times
                flight_dep = outbound_flight.get("departure_time", "") if outbound_flight else ""
                flight_arr = outbound_flight.get("arrival_time", "") if outbound_flight else ""

                if flight_dep and flight_arr:
                    # Full flight data: startTime = origin departure, duration = flight time
                    effective_start = flight_dep
                    start_min = _parse_time_minutes(flight_dep)
                    end_min = _parse_time_minutes(flight_arr)
                    duration_minutes = max(0, end_min - start_min) if end_min > start_min else 120
                else:
                    # Draft mode: use itinerary's arrival/departure directly
                    effective_start = arrival
                    start_min = _parse_time_minutes(arrival)
                    end_min = _parse_time_minutes(departure)
                    duration_minutes = max(0, end_min - start_min) if end_min > start_min else 60

                place_id = _lookup_place_id(name, name_to_place_id)
                items.append({
                    "placeId": place_id or None,
                    "placeName": name,
                    "role": role,
                    "roles": sorted(roles),
                    "startTime": effective_start,
                    "duration": duration_minutes if duration_minutes > 0 else 60,
                    "note": _generate_note(stop),
                })
                continue

            # ── Return departure (destination airport) ──
            if "return_departure" in roles:
                # When flight data exists: include airport wait + flight
                # When no flight data (draft): use itinerary arrival/departure
                flight_dep = return_flight.get("departure_time", "") if return_flight else ""

                effective_start = arrival
                start_min = _parse_time_minutes(arrival)
                if flight_dep:
                    end_min = _parse_time_minutes(flight_dep)
                else:
                    end_min = _parse_time_minutes(departure)
                duration_minutes = max(0, end_min - start_min) if end_min > start_min else 60

                place_id = _lookup_place_id(name, name_to_place_id)
                items.append({
                    "placeId": place_id or None,
                    "placeName": name,
                    "role": role,
                    "roles": sorted(roles),
                    "startTime": effective_start,
                    "duration": duration_minutes if duration_minutes > 0 else 60,
                    "note": _generate_note(stop),
                })
                continue

            # ── End day (hotel overnight) ──
            if "end_day" in roles:
                # Duration spans from arrival tonight to next morning's start_day departure
                next_day_idx = day_idx + 1
                next_departure = start_day_departures.get(next_day_idx, "")

                start_min = _parse_time_minutes(arrival)
                if next_departure:
                    end_min = _parse_time_minutes(next_departure)
                    # Overnight: next morning time is smaller, so add 24h
                    if end_min <= start_min:
                        duration_minutes = (24 * 60 - start_min) + end_min
                    else:
                        duration_minutes = end_min - start_min
                else:
                    # Last night or no next day info — default 10h
                    duration_minutes = 10 * 60

                place_id = _lookup_place_id(name, name_to_place_id)
                items.append({
                    "placeId": place_id or None,
                    "placeName": name,
                    "role": role,
                    "roles": sorted(roles),
                    "startTime": arrival,
                    "duration": duration_minutes,
                    "note": _generate_note(stop),
                })
                continue

            # ── Regular stops (attractions, meals, generic, hotel logistics, etc.) ──

            # Calculate duration
            duration_minutes = 0
            if arrival and departure:
                start_min = _parse_time_minutes(arrival)
                end_min = _parse_time_minutes(departure)
                duration_minutes = max(0, end_min - start_min)

            # Resolve placeId and Note
            place_id = ""
            final_note = _generate_note(stop)
            
            if roles & {"lunch", "dinner"}:
                # Match restaurant by (day_idx, meal_type) — NOT by name
                meal_type = "lunch" if "lunch" in roles else "dinner"
                matched_restaurant = restaurant_by_slot.get((day_idx, meal_type))
                if matched_restaurant:
                    place_id = matched_restaurant.get("place_id", "")
                    # Update name to the actual restaurant name
                    name = matched_restaurant.get("name", name)
                    # Override note with restaurant's note if available
                    if matched_restaurant.get("note"):
                        final_note = matched_restaurant.get("note")
            elif "attraction" in roles:
                place_id = _lookup_place_id(name, name_to_place_id)
            else:
                # Hotel roles (check_in, check_out, luggage_drop, luggage_pickup, rest, start_day)
                # or generic activities
                place_id = _lookup_place_id(name, name_to_place_id)

            if not place_id and roles - SKIP_ROLES - {"generic", "start_day"}:
                logger.warning(f"🔨 [APPLY_DATA] ⚠️ No placeId for stop '{name}' (roles={roles}, day={day_idx})")

            items.append({
                "placeId": place_id or None,
                "placeName": name,
                "role": role,
                "roles": sorted(roles),
                "startTime": arrival,
                "duration": duration_minutes if duration_minutes > 0 else 60,
                "note": final_note,
            })

        days.append({
            "order": day_idx - 1,  # .NET API expects 0-based order
            "title": day_data.get("title") or f"Day {day_idx}",
            "items": items,
        })

    return days


# ── Budget / Expense Items ───────────────────────────────────────────────

def _build_expense_items(
    agent_outputs: dict[str, Any],
    plan_context: dict[str, Any],
    aggregated_costs: dict[str, Any] | None = None,
) -> list[dict]:
    """Flatten aggregated costs into a list of expense items.

    Maps category names from cost_aggregator to .NET ExpenseCategory enum values.
    For the "other" category (from preparation agent), maps using the budget "type" field.
    """
    if not aggregated_costs:
        return []

    items = []

    for cat_key, cat_data in aggregated_costs.get("categories", {}).items():
        dotnet_category = AGGREGATED_CATEGORY_MAP.get(cat_key, "Other")

        for cost_item in cat_data.get("items", []):
            name = cost_item.get("name", "")
            amount = cost_item.get("amount", 0)
            note = cost_item.get("note", "")

            # For "other" category, try to extract more specific mapping
            # from the [Type] prefix in name (e.g. "[Transport] Grab/taxi")
            actual_category = dotnet_category
            if cat_key == "other" and name.startswith("["):
                bracket_end = name.find("]")
                if bracket_end > 0:
                    type_str = name[1:bracket_end].strip()
                    actual_category = PREP_BUDGET_TYPE_MAP.get(type_str, "Other")
                    name = name[bracket_end + 1:].strip()  # Remove [Type] prefix

            display_name = f"{name} ({note})" if note else name

            expense_item = {
                "category": actual_category,
                "name": display_name,
                "amount": amount,
            }
            items.append(expense_item)

    return items


# ── Packing Lists ────────────────────────────────────────────────────────

def _build_packing_lists(agent_outputs: dict[str, Any]) -> list[dict]:
    """Extract packing lists from preparation_agent output."""
    prep_data = agent_outputs.get("preparation_agent", {})
    if not prep_data or prep_data.get("skipped"):
        return []

    result = []
    for pl in prep_data.get("packing_lists", []):
        name = pl.get("name", "")
        items = pl.get("items", [])
        if name and items:
            result.append({
                "name": name,
                "items": items,  # list of strings
            })

    return result


# ── Notes ────────────────────────────────────────────────────────────────

def _build_notes(agent_outputs: dict[str, Any]) -> list[dict]:
    """Extract notes from preparation_agent output."""
    prep_data = agent_outputs.get("preparation_agent", {})
    if not prep_data or prep_data.get("skipped"):
        return []

    result = []
    for note in prep_data.get("notes", []):
        title = note.get("title", "")
        content = note.get("content", "")
        if title and content:
            result.append({
                "title": title,
                "content": content,
            })

    return result


# ── Main Builder ─────────────────────────────────────────────────────────

def build_apply_data(
    agent_outputs: dict[str, Any],
    plan_context: dict[str, Any],
    aggregated_costs: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build normalized apply_data for frontend → .NET Apply endpoint.

    Returns a dict that the frontend can directly use as the body
    for POST /api/Plan/{id}/apply-ai (with mode added by frontend).
    """
    logger.info("🔨 [APPLY_DATA_BUILDER] Building apply_data...")

    itinerary_days = _build_itinerary_days(agent_outputs, plan_context)
    expense_items = _build_expense_items(agent_outputs, plan_context, aggregated_costs)
    packing_lists = _build_packing_lists(agent_outputs)
    notes = _build_notes(agent_outputs)

    apply_data = {
        "startTime": plan_context.get("start_date"),
        "endTime": plan_context.get("end_date"),
        "currencyCode": plan_context.get("currency", "VND"),
        "itineraryDays": itinerary_days,
        "expenseItems": expense_items,
        "packingLists": packing_lists,
        "notes": notes,
    }

    logger.info(
        f"🔨 [APPLY_DATA_BUILDER] Built: "
        f"{len(itinerary_days)} days, "
        f"{len(expense_items)} expense items, "
        f"{len(packing_lists)} packing lists, "
        f"{len(notes)} notes"
    )

    return apply_data


def build_sectioned_apply_data(
    agent_outputs: dict[str, Any],
    plan_context: dict[str, Any],
    aggregated_costs: dict[str, Any] | None = None,
    changed_sections: set[str] | None = None,
) -> dict[str, Any]:
    """Build sectioned apply_data with per-section is_apply flags.

    This format supports partial updates — when modifying only the itinerary,
    only that section has is_apply=true. The full snapshot is still included
    for version control and rollbacks.

    Args:
        agent_outputs: Combined agent outputs from the pipeline
        plan_context: Plan metadata (dates, destination, currency, etc.)
        aggregated_costs: Cost aggregation result (optional)
        changed_sections: Set of section names that were changed this turn.
                          If None, all sections are marked as apply.
                          Valid names: "itinerary", "budget", "packing", "notes"

    Returns:
        {
            "plan_context": { "startTime": "...", "endTime": "...", "currencyCode": "VND" },
            "sections": {
                "itinerary": { "is_apply": true, "data": [...] },
                "budget":    { "is_apply": false, "data": [...] },
                "packing":   { "is_apply": false, "data": [...] },
                "notes":     { "is_apply": false, "data": [...] }
            }
        }
    """
    logger.info("🔨 [APPLY_DATA_BUILDER] Building sectioned apply_data...")

    # If no changed_sections specified, all sections are applied
    if changed_sections is None:
        changed_sections = {"itinerary", "budget", "packing", "notes"}

    itinerary_days = _build_itinerary_days(agent_outputs, plan_context)
    expense_items = _build_expense_items(agent_outputs, plan_context, aggregated_costs)
    packing_lists = _build_packing_lists(agent_outputs)
    notes = _build_notes(agent_outputs)

    sectioned = {
        "plan_context": {
            "startTime": plan_context.get("start_date"),
            "endTime": plan_context.get("end_date"),
            "currencyCode": plan_context.get("currency", "VND"),
        },
        "sections": {
            "itinerary": {
                "is_apply": "itinerary" in changed_sections,
                "data": itinerary_days,
            },
            "budget": {
                "is_apply": "budget" in changed_sections,
                "data": expense_items,
            },
            "packing": {
                "is_apply": "packing" in changed_sections,
                "data": packing_lists,
            },
            "notes": {
                "is_apply": "notes" in changed_sections,
                "data": notes,
            },
        },
    }

    applied = [s for s in changed_sections if s in sectioned["sections"]]
    logger.info(
        f"🔨 [APPLY_DATA_BUILDER] Sectioned: "
        f"applied={applied}, "
        f"{len(itinerary_days)} days, "
        f"{len(expense_items)} expenses, "
        f"{len(packing_lists)} packing, "
        f"{len(notes)} notes"
    )

    return sectioned

