---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	orchestrator(orchestrator)
	flight(flight)
	hotel(hotel)
	attraction(attraction)
	weather(weather)
	itinerary(itinerary)
	restaurant(restaurant)
	preparation(preparation)
	synthesize(synthesize)
	__end__([<p>__end__</p>]):::last
	__start__ --> orchestrator;
	attraction --> itinerary;
	flight --> itinerary;
	hotel --> itinerary;
	itinerary --> preparation;
	itinerary --> restaurant;
	orchestrator -.-> __end__;
	orchestrator -.-> attraction;
	orchestrator -.-> flight;
	orchestrator -.-> hotel;
	orchestrator -.-> weather;
	preparation --> synthesize;
	restaurant --> synthesize;
	weather --> itinerary;
	synthesize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
