---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	intent(intent)
	orchestrator(orchestrator)
	flight(flight)
	hotel(hotel)
	attraction(attraction)
	weather(weather)
	itinerary(itinerary)
	restaurant(restaurant)
	preparation(preparation)
	synthesize(synthesize)
	select_apply(select_apply)
	__end__([<p>__end__</p>]):::last
	__start__ --> intent;
	attraction -.-> itinerary;
	attraction -.-> synthesize;
	flight -.-> itinerary;
	flight -.-> synthesize;
	hotel -.-> itinerary;
	hotel -.-> synthesize;
	intent -.-> __end__;
	intent -.-> attraction;
	intent -.-> flight;
	intent -.-> hotel;
	intent -.-> itinerary;
	intent -.-> orchestrator;
	intent -.-> preparation;
	intent -.-> restaurant;
	intent -.-> select_apply;
	itinerary -.-> preparation;
	itinerary -.-> restaurant;
	itinerary -.-> synthesize;
	orchestrator -.-> __end__;
	orchestrator -.-> attraction;
	orchestrator -.-> flight;
	orchestrator -.-> hotel;
	orchestrator -.-> weather;
	preparation --> synthesize;
	restaurant --> synthesize;
	select_apply -.-> __end__;
	select_apply -.-> itinerary;
	select_apply -.-> synthesize;
	weather --> itinerary;
	synthesize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
